---

- name: Add third-party repository for Ubuntu
  apt_repository: repo={{ ubuntu_php7_ppa_repo }}

- name: apt-get update
  apt:
    update_cache: yes

- name: Install PHP Packages
  apt: name={{ item }} state=present
  with_nested: "{{ apt_php_packages }}"
  notify:
    - restart php7-fpm