---
# defaults file for ansible-role-php7

ubuntu_php7_ppa_repo: "ppa:ondrej/php"

apt_php_packages:
  - php7.1
  - php7.1-cgi
  - php7.1-cli
  - php7.1-common
  - php7.1-curl
  - php7.1-fpm
  - php7.1-gd
  - php7.1-intl
  - php7.1-json
  - php7.1-mysql
  - php7.1-mbstring
