---

- name: Create vhosts
  template:
    src: vhosts.conf.j2
    dest: /etc/nginx/sites-available/{{ item.key }}.conf
  with_dict: "{{ vhosts }}"

- name: Enable vhosts
  file:
    path: /etc/nginx/sites-enabled/{{ item.key }}.conf
    src: /etc/nginx/sites-available/{{ item.key }}.conf
    state: link
  with_dict: "{{ vhosts }}"
  notify:
    - restart nginx